# Generated by Django 6.0.1 on 2026-09-15 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('lesson_watch', 'Lesson Watched'), ('quiz_taken', 'Quiz Taken'), ('quiz_passed', 'Quiz Passed'), ('assignment_submit', 'Assignment Submitted'), ('bounty_attempt', 'Bounty Attempted'), ('bounty_solved', 'Bounty Solved'), ('course_enroll', 'Course Enrolled'), ('chat_message', 'Chat Message Sent'), ('profile_update', 'Profile Updated'), ('course_complete', 'Course Completed'), ('code_review', 'Code Review Requested')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
