# Generated by Django 6.0.6 on 2026-09-16 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='students.librarydocument')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'document')},
            },
        ),
        migrations.CreateModel(
            name='LiveClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='students.liveclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'live_class')},
            },
        ),
    ]
