# Generated by Django 6.0.1 on 2026-10-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_payment_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, default='View Details', help_text='Button text for suitable task', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Direct link to suitable task', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('notice', 'Notice / Announcement'), ('course', 'New Course'), ('lesson', 'New Lesson'), ('live_class', 'Live Class'), ('exam', 'AI Exam / Quiz'), ('document', 'Study Material'), ('assignment', 'Assignment Task'), ('coins', 'LMS Coins Reward'), ('system', 'System Alert')], default='notice', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Target student or null for global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
