# Generated by Django 6.0.1 on 2026-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_notification_action_label_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, help_text='Brief attachment in PDF, DOCX, ZIP, image, etc.', null=True, upload_to='assignments/briefs/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
