# Generated by Django 6.0.1 on 2026-10-10 16:33

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_profile_student_id_user_phone_user_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('notice', 'Notice / Announcement'), ('course', 'New Course'), ('lesson', 'New Lesson'), ('live_class', 'Live Class'), ('exam', 'AI Exam / Quiz'), ('document', 'Study Material'), ('assignment', 'Assignment Task'), ('coins', 'LMS Coins Reward'), ('system', 'System Alert'), ('support', 'Support Ticket / Help Desk')], default='notice', max_length=50),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, default=students.models.generate_ticket_number, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('student_id_code', models.CharField(blank=True, help_text='6-digit Student ID or Roll', max_length=20, null=True)),
                ('source', models.CharField(choices=[('student_profile', 'Student Profile Desk'), ('landing_help_center', 'Landing Help Center'), ('landing_contact_us', 'Landing Contact Us'), ('terms_modal', 'Terms Inquiry')], default='student_profile', max_length=50)),
                ('category', models.CharField(choices=[('password_reset', 'Password Reset / Account Recovery'), ('login_issue', 'Login / Access Problem'), ('course_doubt', 'Course Content / Learning Doubt'), ('payment_coins', 'Payment / Coins / Transaction Issue'), ('technical_bug', 'Technical Glitch / Bug Report'), ('general_query', 'General Inquiry / Guidance'), ('other', 'Other Problem')], default='general_query', max_length=50)),
                ('priority', models.CharField(choices=[('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent / Critical')], default='normal', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
